[package]
name = "wasm_test"
version = "1.0.0"
edition = "2021"
description = "wasm test for the small apps project"

[lib]
crate-type = ["cdylib"]

[profil.release]
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true

[dependencies]
wasm-bindgen = "0.2.89"